image: golang:1.11.2

stages:
  - test
  - acceptanceTest
  - build
  - deploy

cache:
  paths:
    - /go/pkg/mod/

tests/unit:
  stage: test
  script:
    - make .env
    - make test

tests/race:
  stage: test
  script:
    - make .env
    - make race

tests_acceptance:
  stage: acceptanceTest
  script:
    - make testacc

build:
  stage: build
  before_script:
    - apt-get update && apt-get install -y zip
  script:
    - make build-sandbox
    - make build-client
    - make release VERSION=${CI_COMMIT_TAG:-"v0.0.0-${CI_COMMIT_REF_SLUG}"}
  artifacts:
    paths:
      - bin/release
    expire_in: 1 hour

copy_to_s3:
  stage: deploy
  image: kiwicom/s3cmd
  script:
    - s3cmd sync
      --no-preserve
      --no-mime-magic
      --guess-mime-type
      --recursive
      --default-mime-type="application/zip"
      bin/release/* s3://kw-terraform-providers/cphalo/
