image: golang:1.11.4

stages:
  - test
  - acceptanceTest
  - build
  - preReleaseTest
  - release

variables:
  GOPATH: $CI_PROJECT_DIR/go

cache:
  key: $CI_PROJECT_PATH_SLUG-build
  paths:
    - $GOPATH/pkg/mod
#    - /root/.cache/go-build

tests/unit:
  stage: test
  script:
    - make .env
    - make test

tests/race:
  stage: test
  script:
    - make .env
    - make race

tests_acceptance:
  stage: acceptanceTest
  script:
    - make testacc

build:
  stage: build
  before_script:
    - apt-get update && apt-get install -y zip
  script:
    - make build-sandbox
    - make build-client
    - export RELEASE_VERSION=${CI_COMMIT_TAG:-"v0.0.0-${CI_COMMIT_REF_SLUG}"}
    - echo "Building version ${RELEASE_VERSION}"
    - make release VERSION=${RELEASE_VERSION}
  artifacts:
    paths:
      - bin/release
    expire_in: 1 hour

examples_test:
  stage: preReleaseTest
  only:
    refs:
      - master
  variables:
    TERRAFORM_VERSION: 0.11.10
    TERRAFORM_SHA256SUM: 43543a0e56e31b0952ea3623521917e060f2718ab06fe2b2d506cfaa14d54527
  before_script:
    - apt-get update && apt-get install -y zip
    - curl -Ss https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip > terraform_${TERRAFORM_VERSION}_linux_amd64.zip
    - echo "${TERRAFORM_SHA256SUM} terraform_${TERRAFORM_VERSION}_linux_amd64.zip" > terraform_${TERRAFORM_VERSION}_SHA256SUMS
    - sha256sum -c terraform_${TERRAFORM_VERSION}_SHA256SUMS
    - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /bin
    - rm -f terraform_${TERRAFORM_VERSION}_linux_amd64.zip terraform_${TERRAFORM_VERSION}_SHA256SUMS
    - terraform version
  script:
    - export RELEASE_VERSION=${CI_COMMIT_TAG:-"v0.0.0-${CI_COMMIT_REF_SLUG}"}
    - echo "Testing version ${RELEASE_VERSION}"
    - cd ${CI_PROJECT_DIR}/bin/release/${RELEASE_VERSION}
    - shasum -c terraform-provider-cphalo_${RELEASE_VERSION}_linux_amd64.sha256
    - mkdir -p ~/.terraform.d/plugins
    - unzip terraform-provider-cphalo_${RELEASE_VERSION}_linux_amd64.zip
    - mv terraform-provider-cphalo_${RELEASE_VERSION} ~/.terraform.d/plugins
    - rm terraform-provider-cphalo_${RELEASE_VERSION}_linux_amd64.zip readme.md terraform-provider-cphalo_${RELEASE_VERSION}_linux_amd64.sha256
    - cd ${CI_PROJECT_DIR}/examples/basic
    - terraform init
    - terraform apply -auto-approve
    - terraform plan -no-color > output_plan.txt
    - cat output_plan.txt
    - grep "No changes. Infrastructure is up-to-date." output_plan.txt
  after_script:
    - cd ${CI_PROJECT_DIR}/examples/basic
    - terraform destroy -auto-approve

copy_to_s3:
  stage: release
  image: kiwicom/s3cmd
  except:
    - schedules
  script:
    - s3cmd sync
      --no-preserve
      --no-mime-magic
      --guess-mime-type
      --recursive
      --default-mime-type="application/zip"
      bin/release/* s3://kw-terraform-providers/cphalo/
