image: golang:1.11.2

stages:
  - test
  - build

before_script:
  - make .env

tests:
  stage: test
  script:
    - make test

tests_race:
  stage: test
  script:
    - make race

build:
  stage: build
  script:
    - apt-get update && apt-get install -y zip
    - make build-sandbox
    - make build-client
    - make release
    - cp bin/release/*.zip /tmp # TODO: copy this to S3 or something
