image: golang:1.11.2

stages:
  - test
  - acceptanceTest
  - build
  - deploy

tests:
  stage: test
  script:
    - make .env
    - make test

tests_race:
  stage: test
  script:
    - make .env
    - make race

tests_acceptance:
  stage: acceptanceTest
  script:
    - make testacc

build:
  stage: build
  script:
    - apt-get update && apt-get install -y zip
    - make build-sandbox
    - make build-client
    - make release VERSION=alpha
  artifacts:
    paths:
      - bin/release
    expire_in: 1 hour

copy_to_s3:
  stage: deploy
  image: kiwicom/s3cmd
#  only:
#    - master
  script:
    - s3cmd sync
      --no-preserve
      --no-mime-magic
      --guess-mime-type
      --recursive
      --default-mime-type="application/zip"
      bin/release s3://kw-terraform-providers
