theme: book
title: Terraform CloudPassage Halo Provider
baseURL: https://kiwicom.gitlab.io/terraform-provider-cphalo/

disableKinds: ["taxonomy", "taxonomyTerm"]
disablePathToLower: true
enableGitInfo: true

pygmentsuseclasses: false
pygmentscodefences: true
pygmentsStyle: pygments

params:
  BookToC: false
  BookMenuBundle: /menu
  BookRepo: https://gitlab.com/kiwicom/terraform-provider-cphalo
  BookEditPath: /edit/master/website/content
